[package]
name = "lib_core"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
# Inherit lint configuration from the workspace Cargo.toml
workspace = true

[dependencies]
## --- Internal Library Dependencies

## --- Workspace Crate Dependencies
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

## --- Library Dependencies

[build-dependencies]

[dev-dependencies]
