[package]
name = "lib_settings"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
# Inherit lint configuration from the workspace Cargo.toml
workspace = true

[dependencies]
## --- Internal Dependencies
lib_utils = { path = "../lib_utils" }

## --- Workspace Dependencies
thiserror = { workspace = true }
serde = { workspace = true }

## --- Library Dependencies
config = { version = "0.15.19" }
dirs = { version = "6.0.0" }

[dev-dependencies]
serde_json = { version = "1.0" }
