[package]
name = "lib_bitcoind"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
# Inherit lint configuration from the workspace Cargo.toml
workspace = true

[dependencies]
## --- Internal Library Dependencies
lib_settings = { path = "../../libs/lib_settings" }

## --- Workspace Crate Dependencies
secrecy = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

## --- Library Dependencies
corepc-types = { version = "0.15" } # This crate provides data types returned by Bitcoin Core/Knots's JSON-RPC API.
reqwest = { version = "0.13.4", default-features = false, features = ["json"] }

[build-dependencies]


[dev-dependencies]
wiremock = "0.6"
tokio = { workspace = true }
