// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/authentication/authentication.proto" (package "bitnode_console.authentication.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Authentication Service Protocol Buffer Definition
//
// Defines the RPC service and messages for user authentication,
// including login, token refresh, and logout.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthenticationService } from "./authentication";
import type { LogoutResponse } from "./authentication";
import type { LogoutRequest } from "./authentication";
import type { RefreshResponse } from "./authentication";
import type { RefreshRequest } from "./authentication";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { LoginResponse } from "./authentication";
import type { LoginRequest } from "./authentication";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * AuthenticationService handles user authentication and token management.
 *
 * @generated from protobuf service bitnode_console.authentication.v1.AuthenticationService
 */
export interface IAuthenticationServiceClient {
    /**
     * Login authenticates a user with a username and password.
     *
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * Refresh issues a new access token using the refresh token in the request metadata.
     *
     * @generated from protobuf rpc: Refresh
     */
    refresh(input: RefreshRequest, options?: RpcOptions): UnaryCall<RefreshRequest, RefreshResponse>;
    /**
     * Logout invalidates the caller's access and refresh tokens.
     *
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse>;
}
/**
 * AuthenticationService handles user authentication and token management.
 *
 * @generated from protobuf service bitnode_console.authentication.v1.AuthenticationService
 */
export class AuthenticationServiceClient implements IAuthenticationServiceClient, ServiceInfo {
    typeName = AuthenticationService.typeName;
    methods = AuthenticationService.methods;
    options = AuthenticationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Login authenticates a user with a username and password.
     *
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Refresh issues a new access token using the refresh token in the request metadata.
     *
     * @generated from protobuf rpc: Refresh
     */
    refresh(input: RefreshRequest, options?: RpcOptions): UnaryCall<RefreshRequest, RefreshResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<RefreshRequest, RefreshResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Logout invalidates the caller's access and refresh tokens.
     *
     * @generated from protobuf rpc: Logout
     */
    logout(input: LogoutRequest, options?: RpcOptions): UnaryCall<LogoutRequest, LogoutResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutRequest, LogoutResponse>("unary", this._transport, method, opt, input);
    }
}
