# BitNode Console Configuration File
#
# This file contains configuration settings for the BitNode Console application.
# It uses INI format with sections and key-value pairs.
#
# For more information, see the documentation at docs/src/configuration.md

[application]

[bitcoind]
rpc_host = "127.0.0.1"
rpc_port = 8332
rpc_user = "bitcoinrpc"
rpc_password = "devpassword"
unit_name = "bitcoind.service"

[rpc]
host = "127.0.0.1"
port = 50051
# Set to 'yourpassword' for development, default is empty and will stop the server from starting
password_hash = "$argon2id$v=19$m=4096,t=3,p=1$Mzk3NGQ1NDBiZmZiYjhhNDY0YWY3MmRjYjIwNDI2YmE$Bzo73djW0DkCVR4prXhqvWB4ViEdJ54h91mU0LCgqPY"
token_secret = "token-super-secret-2653871"
allowed_ips[0] = 127.0.0.1


[tracing]
enabled = true
show_settings_startup = true
level = "debug"

[web]
host = "localhost"
port = 8086
