// This file is @generated by prost-build.
/// GetLogsRequest specifies how many recent log lines to fetch.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct GetLogsRequest {
    /// Number of most-recent lines to return. Defaults to 100 when zero.
    #[prost(uint32, tag = "1")]
    pub lines: u32,
}
/// GetLogsResponse carries the fetched log entries.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLogsResponse {
    /// Log entries in chronological order (oldest first).
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<LogEntry>,
}
/// StreamLogsRequest initiates a live log tail.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamLogsRequest {
    /// Number of existing lines to emit before streaming new entries.
    #[prost(uint32, tag = "1")]
    pub tail_lines: u32,
}
/// LogEntry represents a single journal log line from the Bitcoin daemon.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogEntry {
    /// Log message text.
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    /// Wall-clock time of the entry in microseconds since the Unix epoch.
    #[prost(int64, tag = "2")]
    pub timestamp_us: i64,
    /// Severity level: one of "emerg", "alert", "crit", "err",
    /// "warning", "notice", "info", or "debug".
    #[prost(string, tag = "3")]
    pub priority: ::prost::alloc::string::String,
    /// Systemd unit or syslog identifier that produced the entry.
    #[prost(string, tag = "4")]
    pub unit: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod journald_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// JournaldService exposes Bitcoin daemon log entries from the systemd journal.
    ///
    /// The unit name read is fixed by server configuration; clients cannot select
    /// an arbitrary unit, preventing authenticated users from reading unrelated logs.
    #[derive(Debug, Clone)]
    pub struct JournaldServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl JournaldServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> JournaldServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> JournaldServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            JournaldServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// GetLogs returns the last N log lines (unary, for initial page load).
        pub async fn get_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::GetLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetLogsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bitnode_console.v1.journald.v1.JournaldService/GetLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bitnode_console.v1.journald.v1.JournaldService",
                        "GetLogs",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// StreamLogs streams new log entries in real time (server-streaming, for live tail).
        pub async fn stream_logs(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamLogsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::LogEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bitnode_console.v1.journald.v1.JournaldService/StreamLogs",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bitnode_console.v1.journald.v1.JournaldService",
                        "StreamLogs",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod journald_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with JournaldServiceServer.
    #[async_trait]
    pub trait JournaldService: std::marker::Send + std::marker::Sync + 'static {
        /// GetLogs returns the last N log lines (unary, for initial page load).
        async fn get_logs(
            &self,
            request: tonic::Request<super::GetLogsRequest>,
        ) -> std::result::Result<tonic::Response<super::GetLogsResponse>, tonic::Status>;
        /// Server streaming response type for the StreamLogs method.
        type StreamLogsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::LogEntry, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// StreamLogs streams new log entries in real time (server-streaming, for live tail).
        async fn stream_logs(
            &self,
            request: tonic::Request<super::StreamLogsRequest>,
        ) -> std::result::Result<tonic::Response<Self::StreamLogsStream>, tonic::Status>;
    }
    /// JournaldService exposes Bitcoin daemon log entries from the systemd journal.
    ///
    /// The unit name read is fixed by server configuration; clients cannot select
    /// an arbitrary unit, preventing authenticated users from reading unrelated logs.
    #[derive(Debug)]
    pub struct JournaldServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> JournaldServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for JournaldServiceServer<T>
    where
        T: JournaldService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/bitnode_console.v1.journald.v1.JournaldService/GetLogs" => {
                    #[allow(non_camel_case_types)]
                    struct GetLogsSvc<T: JournaldService>(pub Arc<T>);
                    impl<
                        T: JournaldService,
                    > tonic::server::UnaryService<super::GetLogsRequest>
                    for GetLogsSvc<T> {
                        type Response = super::GetLogsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JournaldService>::get_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetLogsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bitnode_console.v1.journald.v1.JournaldService/StreamLogs" => {
                    #[allow(non_camel_case_types)]
                    struct StreamLogsSvc<T: JournaldService>(pub Arc<T>);
                    impl<
                        T: JournaldService,
                    > tonic::server::ServerStreamingService<super::StreamLogsRequest>
                    for StreamLogsSvc<T> {
                        type Response = super::LogEntry;
                        type ResponseStream = T::StreamLogsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamLogsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JournaldService>::stream_logs(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamLogsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for JournaldServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "bitnode_console.v1.journald.v1.JournaldService";
    impl<T> tonic::server::NamedService for JournaldServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
