// This file is @generated by prost-build.
/// GetLogsRequest specifies the page of log entries to fetch.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJournalsRequest {
    /// Timestamp to start fetching from.
    #[prost(int64, tag = "1")]
    pub timestamp_from: i64,
    /// Timestamp to end fetching at.
    #[prost(int64, tag = "2")]
    pub timestamp_to: i64,
    /// Minimum severity level to return; defaults to INFO when unspecified.
    #[prost(enumeration = "Priority", tag = "3")]
    pub priority: i32,
    /// Pagination parameters: page size, page token, and direction.
    #[prost(message, optional, tag = "4")]
    pub pagination: ::core::option::Option<super::super::common::v1::PageRequest>,
}
/// GetLogsResponse carries the fetched log entries and the next page token.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetJournalsResponse {
    /// Log entries in chronological order (oldest first).
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<JournalsEntry>,
    /// Pagination cursors and boundary flags for navigating between pages.
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<super::super::common::v1::PageResponse>,
}
/// StreamLogsRequest initiates a live log tail.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct StreamJournalsRequest {
    /// Number of existing lines to emit before streaming new entries.
    #[prost(uint32, tag = "1")]
    pub tail_lines: u32,
}
/// LogEntry represents a single journal log line from the Bitcoin daemon.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct JournalsEntry {
    /// Log message text.
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    /// Wall-clock time of the entry in microseconds since the Unix epoch.
    #[prost(int64, tag = "2")]
    pub timestamp_us: i64,
    /// Severity level of this entry.
    #[prost(enumeration = "Priority", tag = "3")]
    pub priority: i32,
    /// Systemd unit or syslog identifier that produced the entry.
    #[prost(string, tag = "4")]
    pub unit: ::prost::alloc::string::String,
    /// Journal cursor for seeking and pagination; absent when not recorded.
    #[prost(string, optional, tag = "5")]
    pub cursor: ::core::option::Option<::prost::alloc::string::String>,
    /// All remaining journal fields not captured by the fields above.
    #[prost(map = "string, string", tag = "6")]
    pub extra_fields: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Priority mirrors the syslog severity levels from RFC 5424.
///
/// PRIORITY_UNSPECIFIED is the proto3 default and is treated as
/// PRIORITY_INFO by the server.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Priority {
    Unspecified = 0,
    Emergency = 1,
    Alert = 2,
    Critical = 3,
    Error = 4,
    Warning = 5,
    Notice = 6,
    Info = 7,
    Debug = 8,
}
impl Priority {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PRIORITY_UNSPECIFIED",
            Self::Emergency => "PRIORITY_EMERGENCY",
            Self::Alert => "PRIORITY_ALERT",
            Self::Critical => "PRIORITY_CRITICAL",
            Self::Error => "PRIORITY_ERROR",
            Self::Warning => "PRIORITY_WARNING",
            Self::Notice => "PRIORITY_NOTICE",
            Self::Info => "PRIORITY_INFO",
            Self::Debug => "PRIORITY_DEBUG",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PRIORITY_UNSPECIFIED" => Some(Self::Unspecified),
            "PRIORITY_EMERGENCY" => Some(Self::Emergency),
            "PRIORITY_ALERT" => Some(Self::Alert),
            "PRIORITY_CRITICAL" => Some(Self::Critical),
            "PRIORITY_ERROR" => Some(Self::Error),
            "PRIORITY_WARNING" => Some(Self::Warning),
            "PRIORITY_NOTICE" => Some(Self::Notice),
            "PRIORITY_INFO" => Some(Self::Info),
            "PRIORITY_DEBUG" => Some(Self::Debug),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod journals_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// JournalsService exposes Bitcoin daemon log entries from the systemd journal.
    ///
    /// The unit name read is fixed by server configuration; clients cannot select
    /// an arbitrary unit, preventing authenticated users from reading unrelated logs.
    #[derive(Debug, Clone)]
    pub struct JournalsServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl JournalsServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> JournalsServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> JournalsServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            JournalsServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// GetLogs returns a page of log lines (unary, for initial page load and pagination).
        pub async fn get_journals(
            &mut self,
            request: impl tonic::IntoRequest<super::GetJournalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetJournalsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bitnode_console.journals.v1.JournalsService/GetJournals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bitnode_console.journals.v1.JournalsService",
                        "GetJournals",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// StreamLogs streams new log entries in real time (server-streaming, for live tail).
        /// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
        pub async fn stream_journals(
            &mut self,
            request: impl tonic::IntoRequest<super::StreamJournalsRequest>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::JournalsEntry>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/bitnode_console.journals.v1.JournalsService/StreamJournals",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "bitnode_console.journals.v1.JournalsService",
                        "StreamJournals",
                    ),
                );
            self.inner.server_streaming(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod journals_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with JournalsServiceServer.
    #[async_trait]
    pub trait JournalsService: std::marker::Send + std::marker::Sync + 'static {
        /// GetLogs returns a page of log lines (unary, for initial page load and pagination).
        async fn get_journals(
            &self,
            request: tonic::Request<super::GetJournalsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetJournalsResponse>,
            tonic::Status,
        >;
        /// Server streaming response type for the StreamJournals method.
        type StreamJournalsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::JournalsEntry, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// StreamLogs streams new log entries in real time (server-streaming, for live tail).
        /// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
        async fn stream_journals(
            &self,
            request: tonic::Request<super::StreamJournalsRequest>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamJournalsStream>,
            tonic::Status,
        >;
    }
    /// JournalsService exposes Bitcoin daemon log entries from the systemd journal.
    ///
    /// The unit name read is fixed by server configuration; clients cannot select
    /// an arbitrary unit, preventing authenticated users from reading unrelated logs.
    #[derive(Debug)]
    pub struct JournalsServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> JournalsServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for JournalsServiceServer<T>
    where
        T: JournalsService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/bitnode_console.journals.v1.JournalsService/GetJournals" => {
                    #[allow(non_camel_case_types)]
                    struct GetJournalsSvc<T: JournalsService>(pub Arc<T>);
                    impl<
                        T: JournalsService,
                    > tonic::server::UnaryService<super::GetJournalsRequest>
                    for GetJournalsSvc<T> {
                        type Response = super::GetJournalsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetJournalsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JournalsService>::get_journals(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetJournalsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/bitnode_console.journals.v1.JournalsService/StreamJournals" => {
                    #[allow(non_camel_case_types)]
                    struct StreamJournalsSvc<T: JournalsService>(pub Arc<T>);
                    impl<
                        T: JournalsService,
                    > tonic::server::ServerStreamingService<super::StreamJournalsRequest>
                    for StreamJournalsSvc<T> {
                        type Response = super::JournalsEntry;
                        type ResponseStream = T::StreamJournalsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::StreamJournalsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as JournalsService>::stream_journals(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamJournalsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.server_streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for JournalsServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "bitnode_console.journals.v1.JournalsService";
    impl<T> tonic::server::NamedService for JournalsServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
