// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/v1/utilities/utilities.proto" (package "bitnode_console.v1.utilities.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Utilities Service Protocol Buffer Definition
//
// Defines the RPC service and messages for utility operations,
// such as health-check pings.
//
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * PingRequest carries no payload; the RPC is a pure health check.
 *
 * @generated from protobuf message bitnode_console.v1.utilities.v1.PingRequest
 */
export interface PingRequest {
}
/**
 * PingResponse confirms that the server received the ping.
 *
 * @generated from protobuf message bitnode_console.v1.utilities.v1.PingResponse
 */
export interface PingResponse {
    /**
     * Human-readable confirmation, e.g. "pong".
     *
     * @generated from protobuf field: string pong = 1
     */
    pong: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class PingRequest$Type extends MessageType<PingRequest> {
    constructor() {
        super("bitnode_console.v1.utilities.v1.PingRequest", []);
    }
    create(value?: PartialMessage<PingRequest>): PingRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<PingRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PingRequest): PingRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PingRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.v1.utilities.v1.PingRequest
 */
export const PingRequest = new PingRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PingResponse$Type extends MessageType<PingResponse> {
    constructor() {
        super("bitnode_console.v1.utilities.v1.PingResponse", [
            { no: 1, name: "pong", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PingResponse>): PingResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pong = "";
        if (value !== undefined)
            reflectionMergePartial<PingResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PingResponse): PingResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string pong */ 1:
                    message.pong = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PingResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string pong = 1; */
        if (message.pong !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.pong);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.v1.utilities.v1.PingResponse
 */
export const PingResponse = new PingResponse$Type();
/**
 * @generated ServiceType for protobuf service bitnode_console.v1.utilities.v1.UtilitiesService
 */
export const UtilitiesService = new ServiceType("bitnode_console.v1.utilities.v1.UtilitiesService", [
    { name: "Ping", options: {}, I: PingRequest, O: PingResponse }
]);
