// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/common/pagination.proto" (package "bitnode_console.common.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Common Pagination Definition
//
// Reusable cursor/keyset pagination messages shared across services.
// Embed PageRequest in RPC request messages and PageResponse in RPC
// response messages to add consistent bidirectional page navigation.
//
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * PageRequest carries cursor-based pagination parameters for a single page.
 *
 * @generated from protobuf message bitnode_console.common.v1.PageRequest
 */
export interface PageRequest {
    /**
     * Maximum number of items to return. The server may return fewer.
     * Zero lets the server choose a default.
     *
     * @generated from protobuf field: uint32 page_size = 1
     */
    pageSize: number;
    /**
     * Opaque page token from a previous PageResponse marking the page boundary.
     * Omit to start at the natural beginning (DIRECTION_FORWARD) or end
     * (DIRECTION_BACKWARD) of the result set.
     *
     * @generated from protobuf field: optional string page_token = 2
     */
    pageToken?: string;
    /**
     * Direction controls which side of the page token to read from.
     * Defaults to DIRECTION_FORWARD when unspecified.
     *
     * @generated from protobuf field: bitnode_console.common.v1.Direction direction = 3
     */
    direction: Direction;
}
/**
 * PageResponse carries the page tokens and boundary flags needed to navigate
 * between pages. Embed this in RPC response messages alongside the result list.
 *
 * @generated from protobuf message bitnode_console.common.v1.PageResponse
 */
export interface PageResponse {
    /**
     * Pass as page_token in the next request to fetch the page after this one
     * (chronologically newer for logs). Absent when has_next_page is false.
     *
     * @generated from protobuf field: optional string next_page_token = 1
     */
    nextPageToken?: string;
    /**
     * Pass as page_token in the next request to fetch the page before this one
     * (chronologically older for logs). Absent when has_prev_page is false.
     *
     * @generated from protobuf field: optional string prev_page_token = 2
     */
    prevPageToken?: string;
    /**
     * True when at least one more page exists in the DIRECTION_FORWARD direction.
     *
     * @generated from protobuf field: bool has_next_page = 3
     */
    hasNextPage: boolean;
    /**
     * True when at least one more page exists in the DIRECTION_BACKWARD direction.
     *
     * @generated from protobuf field: bool has_prev_page = 4
     */
    hasPrevPage: boolean;
}
/**
 * Direction controls which side of the pagination cursor to read from.
 *
 * @generated from protobuf enum bitnode_console.common.v1.Direction
 */
export enum Direction {
    /**
     * Unspecified defaults to DIRECTION_FORWARD.
     *
     * @generated from protobuf enum value: DIRECTION_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * DIRECTION_FORWARD reads items after the cursor (chronologically newer for logs).
     *
     * @generated from protobuf enum value: DIRECTION_FORWARD = 1;
     */
    FORWARD = 1,
    /**
     * DIRECTION_BACKWARD reads items before the cursor (chronologically older for logs).
     *
     * @generated from protobuf enum value: DIRECTION_BACKWARD = 2;
     */
    BACKWARD = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class PageRequest$Type extends MessageType<PageRequest> {
    constructor() {
        super("bitnode_console.common.v1.PageRequest", [
            { no: 1, name: "page_size", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "page_token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "direction", kind: "enum", T: () => ["bitnode_console.common.v1.Direction", Direction, "DIRECTION_"] }
        ]);
    }
    create(value?: PartialMessage<PageRequest>): PageRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pageSize = 0;
        message.direction = 0;
        if (value !== undefined)
            reflectionMergePartial<PageRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageRequest): PageRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 page_size */ 1:
                    message.pageSize = reader.uint32();
                    break;
                case /* optional string page_token */ 2:
                    message.pageToken = reader.string();
                    break;
                case /* bitnode_console.common.v1.Direction direction */ 3:
                    message.direction = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 page_size = 1; */
        if (message.pageSize !== 0)
            writer.tag(1, WireType.Varint).uint32(message.pageSize);
        /* optional string page_token = 2; */
        if (message.pageToken !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.pageToken);
        /* bitnode_console.common.v1.Direction direction = 3; */
        if (message.direction !== 0)
            writer.tag(3, WireType.Varint).int32(message.direction);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.common.v1.PageRequest
 */
export const PageRequest = new PageRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PageResponse$Type extends MessageType<PageResponse> {
    constructor() {
        super("bitnode_console.common.v1.PageResponse", [
            { no: 1, name: "next_page_token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "prev_page_token", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "has_next_page", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "has_prev_page", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PageResponse>): PageResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.hasNextPage = false;
        message.hasPrevPage = false;
        if (value !== undefined)
            reflectionMergePartial<PageResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PageResponse): PageResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional string next_page_token */ 1:
                    message.nextPageToken = reader.string();
                    break;
                case /* optional string prev_page_token */ 2:
                    message.prevPageToken = reader.string();
                    break;
                case /* bool has_next_page */ 3:
                    message.hasNextPage = reader.bool();
                    break;
                case /* bool has_prev_page */ 4:
                    message.hasPrevPage = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PageResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional string next_page_token = 1; */
        if (message.nextPageToken !== undefined)
            writer.tag(1, WireType.LengthDelimited).string(message.nextPageToken);
        /* optional string prev_page_token = 2; */
        if (message.prevPageToken !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.prevPageToken);
        /* bool has_next_page = 3; */
        if (message.hasNextPage !== false)
            writer.tag(3, WireType.Varint).bool(message.hasNextPage);
        /* bool has_prev_page = 4; */
        if (message.hasPrevPage !== false)
            writer.tag(4, WireType.Varint).bool(message.hasPrevPage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.common.v1.PageResponse
 */
export const PageResponse = new PageResponse$Type();
