// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/bitcoind/bitcoin_daemon.proto" (package "bitnode_console.bitcoin_daemon.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Bitcoin Daemon Service Protocol Buffer Definition
//
// Defines the RPC service and messages for reading the status
// from the Bitcoin Knots/Core daemon (bitcoind). All data is sourced
// from the daemon's JSON-RPC API;
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BitcoinDaemonService } from "./bitcoin_daemon";
import type { NetworkInfoResponse } from "./bitcoin_daemon";
import type { NetworkInfoRequest } from "./bitcoin_daemon";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { BlockchainInfoResponse } from "./bitcoin_daemon";
import type { BlockchainInfoRequest } from "./bitcoin_daemon";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * BitcoinDaemonService exposeses Bitcoin daemon status for the
 * dashboard.
 *
 * @generated from protobuf service bitnode_console.bitcoin_daemon.v1.BitcoinDaemonService
 */
export interface IBitcoinDaemonServiceClient {
    /**
     * BlockchainInfo returns the current state of the block chain,
     * including sync progress and disk usage.
     *
     * @generated from protobuf rpc: BlockchainInfo
     */
    blockchainInfo(input: BlockchainInfoRequest, options?: RpcOptions): UnaryCall<BlockchainInfoRequest, BlockchainInfoResponse>;
    /**
     * NetworkInfo returns the daemon's network configuration and
     * per-transport reachability.
     *
     * Future: rpc PeerInfo, rpc Uptime, rpc MempoolInfo, rpc NetTotals …
     *
     * @generated from protobuf rpc: NetworkInfo
     */
    networkInfo(input: NetworkInfoRequest, options?: RpcOptions): UnaryCall<NetworkInfoRequest, NetworkInfoResponse>;
}
/**
 * BitcoinDaemonService exposeses Bitcoin daemon status for the
 * dashboard.
 *
 * @generated from protobuf service bitnode_console.bitcoin_daemon.v1.BitcoinDaemonService
 */
export class BitcoinDaemonServiceClient implements IBitcoinDaemonServiceClient, ServiceInfo {
    typeName = BitcoinDaemonService.typeName;
    methods = BitcoinDaemonService.methods;
    options = BitcoinDaemonService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * BlockchainInfo returns the current state of the block chain,
     * including sync progress and disk usage.
     *
     * @generated from protobuf rpc: BlockchainInfo
     */
    blockchainInfo(input: BlockchainInfoRequest, options?: RpcOptions): UnaryCall<BlockchainInfoRequest, BlockchainInfoResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<BlockchainInfoRequest, BlockchainInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * NetworkInfo returns the daemon's network configuration and
     * per-transport reachability.
     *
     * Future: rpc PeerInfo, rpc Uptime, rpc MempoolInfo, rpc NetTotals …
     *
     * @generated from protobuf rpc: NetworkInfo
     */
    networkInfo(input: NetworkInfoRequest, options?: RpcOptions): UnaryCall<NetworkInfoRequest, NetworkInfoResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<NetworkInfoRequest, NetworkInfoResponse>("unary", this._transport, method, opt, input);
    }
}
