// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/bitcoind/bitcoin_daemon.proto" (package "bitnode_console.bitcoin_daemon.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Bitcoin Daemon Service Protocol Buffer Definition
//
// Defines the RPC service and messages for reading the status
// from the Bitcoin Knots/Core daemon (bitcoind). All data is sourced
// from the daemon's JSON-RPC API;
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * BlockchainInfoRequest has no parameters; the daemon connection is
 * determined solely by server configuration.
 *
 * @generated from protobuf message bitnode_console.bitcoin_daemon.v1.BlockchainInfoRequest
 */
export interface BlockchainInfoRequest {
}
/**
 * NetworkInfoRequest has no parameters; the daemon connection is
 * determined solely by server configuration.
 *
 * @generated from protobuf message bitnode_console.bitcoin_daemon.v1.NetworkInfoRequest
 */
export interface NetworkInfoRequest {
}
/**
 * BlockchainInfoResponse carries the fields returned by the bitcoind
 * `getblockchaininfo` JSON-RPC call that are relevant to the dashboard.
 *
 * @generated from protobuf message bitnode_console.bitcoin_daemon.v1.BlockchainInfoResponse
 */
export interface BlockchainInfoResponse {
    /**
     * Name of the current network: "main", "test", "signet", or "regtest".
     *
     * @generated from protobuf field: string chain = 1
     */
    chain: string;
    /**
     * Height of the most-work fully-validated chain (i.e. the tip block number).
     *
     * @generated from protobuf field: uint64 blocks = 2
     */
    blocks: string;
    /**
     * Height of the best block header downloaded so far; may exceed `blocks`
     * while the node is still validating.
     *
     * @generated from protobuf field: uint64 headers = 3
     */
    headers: string;
    /**
     * Estimated fraction of the chain that has been verified, in [0.0, 1.0].
     * Reaches 1.0 once the node is fully synced.
     *
     * @generated from protobuf field: double verification_progress = 4
     */
    verificationProgress: number;
    /**
     * True while the node is in Initial Block Download (IBD) mode,
     * i.e. still catching up to the chain tip.
     *
     * @generated from protobuf field: bool initial_block_download = 5
     */
    initialBlockDownload: boolean;
    /**
     * Total size of all block and undo files on disk, in bytes.
     *
     * @generated from protobuf field: uint64 size_on_disk = 6
     */
    sizeOnDisk: string;
    /**
     * True if pruning is enabled; old block files are deleted to save space.
     *
     * @generated from protobuf field: bool pruned = 7
     */
    pruned: boolean;
}
/**
 * NetworkInfoResponse carries the fields returned by the bitcoind
 * `getnetworkinfo` JSON-RPC call that are relevant to the dashboard.
 *
 * @generated from protobuf message bitnode_console.bitcoin_daemon.v1.NetworkInfoResponse
 */
export interface NetworkInfoResponse {
    /**
     * Daemon protocol version number (e.g. 70016).
     *
     * @generated from protobuf field: uint64 version = 1
     */
    version: string;
    /**
     * Human-readable implementation name derived from the user-agent string
     * advertised to peers (e.g. "Bitcoin Core" or "Bitcoin Knots").
     *
     * @generated from protobuf field: string implementation = 2
     */
    implementation: string;
    /**
     * Total number of open peer connections (inbound + outbound).
     *
     * @generated from protobuf field: uint32 connections = 3
     */
    connections: number;
    /**
     * Number of inbound peer connections.
     *
     * @generated from protobuf field: uint32 connections_in = 4
     */
    connectionsIn: number;
    /**
     * Number of outbound peer connections.
     *
     * @generated from protobuf field: uint32 connections_out = 5
     */
    connectionsOut: number;
    /**
     * Reachability status for each network transport the daemon knows about.
     *
     * @generated from protobuf field: repeated bitnode_console.bitcoin_daemon.v1.NetworkReachability networks = 6
     */
    networks: NetworkReachability[];
}
/**
 * NetworkReachability describes whether a specific network transport is
 * reachable from this daemon.
 *
 * @generated from protobuf message bitnode_console.bitcoin_daemon.v1.NetworkReachability
 */
export interface NetworkReachability {
    /**
     * Transport name: one of "ipv4", "ipv6", "onion", "i2p", or "cjdns".
     *
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * True if the daemon can reach peers over this transport.
     *
     * @generated from protobuf field: bool reachable = 2
     */
    reachable: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class BlockchainInfoRequest$Type extends MessageType<BlockchainInfoRequest> {
    constructor() {
        super("bitnode_console.bitcoin_daemon.v1.BlockchainInfoRequest", []);
    }
    create(value?: PartialMessage<BlockchainInfoRequest>): BlockchainInfoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<BlockchainInfoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockchainInfoRequest): BlockchainInfoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlockchainInfoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.bitcoin_daemon.v1.BlockchainInfoRequest
 */
export const BlockchainInfoRequest = new BlockchainInfoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NetworkInfoRequest$Type extends MessageType<NetworkInfoRequest> {
    constructor() {
        super("bitnode_console.bitcoin_daemon.v1.NetworkInfoRequest", []);
    }
    create(value?: PartialMessage<NetworkInfoRequest>): NetworkInfoRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<NetworkInfoRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NetworkInfoRequest): NetworkInfoRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NetworkInfoRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.bitcoin_daemon.v1.NetworkInfoRequest
 */
export const NetworkInfoRequest = new NetworkInfoRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class BlockchainInfoResponse$Type extends MessageType<BlockchainInfoResponse> {
    constructor() {
        super("bitnode_console.bitcoin_daemon.v1.BlockchainInfoResponse", [
            { no: 1, name: "chain", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "blocks", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 3, name: "headers", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 4, name: "verification_progress", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "initial_block_download", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "size_on_disk", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 7, name: "pruned", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<BlockchainInfoResponse>): BlockchainInfoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.chain = "";
        message.blocks = "0";
        message.headers = "0";
        message.verificationProgress = 0;
        message.initialBlockDownload = false;
        message.sizeOnDisk = "0";
        message.pruned = false;
        if (value !== undefined)
            reflectionMergePartial<BlockchainInfoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: BlockchainInfoResponse): BlockchainInfoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string chain */ 1:
                    message.chain = reader.string();
                    break;
                case /* uint64 blocks */ 2:
                    message.blocks = reader.uint64().toString();
                    break;
                case /* uint64 headers */ 3:
                    message.headers = reader.uint64().toString();
                    break;
                case /* double verification_progress */ 4:
                    message.verificationProgress = reader.double();
                    break;
                case /* bool initial_block_download */ 5:
                    message.initialBlockDownload = reader.bool();
                    break;
                case /* uint64 size_on_disk */ 6:
                    message.sizeOnDisk = reader.uint64().toString();
                    break;
                case /* bool pruned */ 7:
                    message.pruned = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: BlockchainInfoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string chain = 1; */
        if (message.chain !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.chain);
        /* uint64 blocks = 2; */
        if (message.blocks !== "0")
            writer.tag(2, WireType.Varint).uint64(message.blocks);
        /* uint64 headers = 3; */
        if (message.headers !== "0")
            writer.tag(3, WireType.Varint).uint64(message.headers);
        /* double verification_progress = 4; */
        if (message.verificationProgress !== 0)
            writer.tag(4, WireType.Bit64).double(message.verificationProgress);
        /* bool initial_block_download = 5; */
        if (message.initialBlockDownload !== false)
            writer.tag(5, WireType.Varint).bool(message.initialBlockDownload);
        /* uint64 size_on_disk = 6; */
        if (message.sizeOnDisk !== "0")
            writer.tag(6, WireType.Varint).uint64(message.sizeOnDisk);
        /* bool pruned = 7; */
        if (message.pruned !== false)
            writer.tag(7, WireType.Varint).bool(message.pruned);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.bitcoin_daemon.v1.BlockchainInfoResponse
 */
export const BlockchainInfoResponse = new BlockchainInfoResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NetworkInfoResponse$Type extends MessageType<NetworkInfoResponse> {
    constructor() {
        super("bitnode_console.bitcoin_daemon.v1.NetworkInfoResponse", [
            { no: 1, name: "version", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "implementation", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "connections", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "connections_in", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "connections_out", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "networks", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => NetworkReachability }
        ]);
    }
    create(value?: PartialMessage<NetworkInfoResponse>): NetworkInfoResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.version = "0";
        message.implementation = "";
        message.connections = 0;
        message.connectionsIn = 0;
        message.connectionsOut = 0;
        message.networks = [];
        if (value !== undefined)
            reflectionMergePartial<NetworkInfoResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NetworkInfoResponse): NetworkInfoResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 version */ 1:
                    message.version = reader.uint64().toString();
                    break;
                case /* string implementation */ 2:
                    message.implementation = reader.string();
                    break;
                case /* uint32 connections */ 3:
                    message.connections = reader.uint32();
                    break;
                case /* uint32 connections_in */ 4:
                    message.connectionsIn = reader.uint32();
                    break;
                case /* uint32 connections_out */ 5:
                    message.connectionsOut = reader.uint32();
                    break;
                case /* repeated bitnode_console.bitcoin_daemon.v1.NetworkReachability networks */ 6:
                    message.networks.push(NetworkReachability.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NetworkInfoResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 version = 1; */
        if (message.version !== "0")
            writer.tag(1, WireType.Varint).uint64(message.version);
        /* string implementation = 2; */
        if (message.implementation !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.implementation);
        /* uint32 connections = 3; */
        if (message.connections !== 0)
            writer.tag(3, WireType.Varint).uint32(message.connections);
        /* uint32 connections_in = 4; */
        if (message.connectionsIn !== 0)
            writer.tag(4, WireType.Varint).uint32(message.connectionsIn);
        /* uint32 connections_out = 5; */
        if (message.connectionsOut !== 0)
            writer.tag(5, WireType.Varint).uint32(message.connectionsOut);
        /* repeated bitnode_console.bitcoin_daemon.v1.NetworkReachability networks = 6; */
        for (let i = 0; i < message.networks.length; i++)
            NetworkReachability.internalBinaryWrite(message.networks[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.bitcoin_daemon.v1.NetworkInfoResponse
 */
export const NetworkInfoResponse = new NetworkInfoResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NetworkReachability$Type extends MessageType<NetworkReachability> {
    constructor() {
        super("bitnode_console.bitcoin_daemon.v1.NetworkReachability", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "reachable", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<NetworkReachability>): NetworkReachability {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.reachable = false;
        if (value !== undefined)
            reflectionMergePartial<NetworkReachability>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: NetworkReachability): NetworkReachability {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* bool reachable */ 2:
                    message.reachable = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: NetworkReachability, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* bool reachable = 2; */
        if (message.reachable !== false)
            writer.tag(2, WireType.Varint).bool(message.reachable);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.bitcoin_daemon.v1.NetworkReachability
 */
export const NetworkReachability = new NetworkReachability$Type();
/**
 * @generated ServiceType for protobuf service bitnode_console.bitcoin_daemon.v1.BitcoinDaemonService
 */
export const BitcoinDaemonService = new ServiceType("bitnode_console.bitcoin_daemon.v1.BitcoinDaemonService", [
    { name: "BlockchainInfo", options: {}, I: BlockchainInfoRequest, O: BlockchainInfoResponse },
    { name: "NetworkInfo", options: {}, I: NetworkInfoRequest, O: NetworkInfoResponse }
]);
