// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/journals/journals.proto" (package "bitnode_console.journals.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Journals Service Protocol Buffer Definition
//
// Defines the RPC service and messages for reading Bitcoin daemon
// log entries from the systemd journal.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { JournalsService } from "./journals";
import type { JournalsEntry } from "./journals";
import type { StreamJournalsRequest } from "./journals";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetJournalsResponse } from "./journals";
import type { GetJournalsRequest } from "./journals";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * JournalsService exposes Bitcoin daemon log entries from the systemd journal.
 *
 * The unit name read is fixed by server configuration; clients cannot select
 * an arbitrary unit, preventing authenticated users from reading unrelated logs.
 *
 * @generated from protobuf service bitnode_console.journals.v1.JournalsService
 */
export interface IJournalsServiceClient {
    /**
     * GetLogs returns a page of log lines (unary, for initial page load and pagination).
     *
     * @generated from protobuf rpc: GetJournals
     */
    getJournals(input: GetJournalsRequest, options?: RpcOptions): UnaryCall<GetJournalsRequest, GetJournalsResponse>;
    /**
     * StreamLogs streams new log entries in real time (server-streaming, for live tail).
     *
     * @generated from protobuf rpc: StreamJournals
     */
    streamJournals(input: StreamJournalsRequest, options?: RpcOptions): ServerStreamingCall<StreamJournalsRequest, JournalsEntry>;
}
/**
 * JournalsService exposes Bitcoin daemon log entries from the systemd journal.
 *
 * The unit name read is fixed by server configuration; clients cannot select
 * an arbitrary unit, preventing authenticated users from reading unrelated logs.
 *
 * @generated from protobuf service bitnode_console.journals.v1.JournalsService
 */
export class JournalsServiceClient implements IJournalsServiceClient, ServiceInfo {
    typeName = JournalsService.typeName;
    methods = JournalsService.methods;
    options = JournalsService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetLogs returns a page of log lines (unary, for initial page load and pagination).
     *
     * @generated from protobuf rpc: GetJournals
     */
    getJournals(input: GetJournalsRequest, options?: RpcOptions): UnaryCall<GetJournalsRequest, GetJournalsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetJournalsRequest, GetJournalsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * StreamLogs streams new log entries in real time (server-streaming, for live tail).
     *
     * @generated from protobuf rpc: StreamJournals
     */
    streamJournals(input: StreamJournalsRequest, options?: RpcOptions): ServerStreamingCall<StreamJournalsRequest, JournalsEntry> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamJournalsRequest, JournalsEntry>("serverStreaming", this._transport, method, opt, input);
    }
}
