// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/journals/journals.proto" (package "bitnode_console.journals.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Journals Service Protocol Buffer Definition
//
// Defines the RPC service and messages for reading Bitcoin daemon
// log entries from the systemd journal.
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PageResponse } from "../common/pagination";
import { PageRequest } from "../common/pagination";
/**
 * GetJournalsRequest specifies the time range, priority filter, and page for
 * log entries to fetch.
 *
 * @generated from protobuf message bitnode_console.journals.v1.GetJournalsRequest
 */
export interface GetJournalsRequest {
    /**
     * Inclusive lower bound; microseconds since the Unix epoch.
     * Omit to start from the beginning of the journal.
     *
     * @generated from protobuf field: optional int64 timestamp_from_us = 1
     */
    timestampFromUs?: string;
    /**
     * Exclusive upper bound; microseconds since the Unix epoch.
     * Omit to read up to the most recent entry.
     *
     * @generated from protobuf field: optional int64 timestamp_to_us = 2
     */
    timestampToUs?: string;
    /**
     * Minimum severity level to return.
     * Omit (or PRIORITY_UNSPECIFIED) to default to PRIORITY_INFO on the server.
     *
     * @generated from protobuf field: optional bitnode_console.journals.v1.Priority priority = 3
     */
    priority?: Priority;
    /**
     * Pagination parameters: page size, page token, and direction.
     *
     * @generated from protobuf field: bitnode_console.common.v1.PageRequest pagination = 4
     */
    pagination?: PageRequest;
}
/**
 * GetLogsResponse carries the fetched log entries and the next page token.
 *
 * @generated from protobuf message bitnode_console.journals.v1.GetJournalsResponse
 */
export interface GetJournalsResponse {
    /**
     * Log entries in chronological order (oldest first).
     *
     * @generated from protobuf field: repeated bitnode_console.journals.v1.JournalsEntry entries = 1
     */
    entries: JournalsEntry[];
    /**
     * Pagination cursors and boundary flags for navigating between pages.
     *
     * @generated from protobuf field: bitnode_console.common.v1.PageResponse pagination = 2
     */
    pagination?: PageResponse;
}
/**
 * StreamLogsRequest initiates a live log tail.
 *
 * @generated from protobuf message bitnode_console.journals.v1.StreamJournalsRequest
 */
export interface StreamJournalsRequest {
    /**
     * Number of existing lines to emit before streaming new entries.
     *
     * @generated from protobuf field: uint32 tail_lines = 1
     */
    tailLines: number;
}
/**
 * LogEntry represents a single journal log line from the Bitcoin daemon.
 *
 * @generated from protobuf message bitnode_console.journals.v1.JournalsEntry
 */
export interface JournalsEntry {
    /**
     * Log message text.
     *
     * @generated from protobuf field: string message = 1
     */
    message: string;
    /**
     * Wall-clock time of the entry in microseconds since the Unix epoch.
     *
     * @generated from protobuf field: int64 timestamp_us = 2
     */
    timestampUs: string;
    /**
     * Severity level of this entry.
     *
     * @generated from protobuf field: bitnode_console.journals.v1.Priority priority = 3
     */
    priority: Priority;
    /**
     * Systemd unit or syslog identifier that produced the entry.
     *
     * @generated from protobuf field: string unit = 4
     */
    unit: string;
    /**
     * Journal cursor for seeking and pagination; absent when not recorded.
     *
     * @generated from protobuf field: optional string cursor = 5
     */
    cursor?: string;
    /**
     * All remaining journal fields not captured by the fields above.
     *
     * @generated from protobuf field: map<string, string> extra_fields = 6
     */
    extraFields: {
        [key: string]: string;
    };
}
/**
 * Priority mirrors the syslog severity levels from RFC 5424.
 *
 * PRIORITY_UNSPECIFIED is the proto3 default and is treated as
 * PRIORITY_INFO by the server.
 *
 * @generated from protobuf enum bitnode_console.journals.v1.Priority
 */
export enum Priority {
    /**
     * @generated from protobuf enum value: PRIORITY_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: PRIORITY_EMERGENCY = 1;
     */
    EMERGENCY = 1,
    /**
     * @generated from protobuf enum value: PRIORITY_ALERT = 2;
     */
    ALERT = 2,
    /**
     * @generated from protobuf enum value: PRIORITY_CRITICAL = 3;
     */
    CRITICAL = 3,
    /**
     * @generated from protobuf enum value: PRIORITY_ERROR = 4;
     */
    ERROR = 4,
    /**
     * @generated from protobuf enum value: PRIORITY_WARNING = 5;
     */
    WARNING = 5,
    /**
     * @generated from protobuf enum value: PRIORITY_NOTICE = 6;
     */
    NOTICE = 6,
    /**
     * @generated from protobuf enum value: PRIORITY_INFO = 7;
     */
    INFO = 7,
    /**
     * @generated from protobuf enum value: PRIORITY_DEBUG = 8;
     */
    DEBUG = 8
}
// @generated message type with reflection information, may provide speed optimized methods
class GetJournalsRequest$Type extends MessageType<GetJournalsRequest> {
    constructor() {
        super("bitnode_console.journals.v1.GetJournalsRequest", [
            { no: 1, name: "timestamp_from_us", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 2, name: "timestamp_to_us", kind: "scalar", opt: true, T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "priority", kind: "enum", opt: true, T: () => ["bitnode_console.journals.v1.Priority", Priority, "PRIORITY_"] },
            { no: 4, name: "pagination", kind: "message", T: () => PageRequest }
        ]);
    }
    create(value?: PartialMessage<GetJournalsRequest>): GetJournalsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetJournalsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetJournalsRequest): GetJournalsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional int64 timestamp_from_us */ 1:
                    message.timestampFromUs = reader.int64().toString();
                    break;
                case /* optional int64 timestamp_to_us */ 2:
                    message.timestampToUs = reader.int64().toString();
                    break;
                case /* optional bitnode_console.journals.v1.Priority priority */ 3:
                    message.priority = reader.int32();
                    break;
                case /* bitnode_console.common.v1.PageRequest pagination */ 4:
                    message.pagination = PageRequest.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetJournalsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional int64 timestamp_from_us = 1; */
        if (message.timestampFromUs !== undefined)
            writer.tag(1, WireType.Varint).int64(message.timestampFromUs);
        /* optional int64 timestamp_to_us = 2; */
        if (message.timestampToUs !== undefined)
            writer.tag(2, WireType.Varint).int64(message.timestampToUs);
        /* optional bitnode_console.journals.v1.Priority priority = 3; */
        if (message.priority !== undefined)
            writer.tag(3, WireType.Varint).int32(message.priority);
        /* bitnode_console.common.v1.PageRequest pagination = 4; */
        if (message.pagination)
            PageRequest.internalBinaryWrite(message.pagination, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.journals.v1.GetJournalsRequest
 */
export const GetJournalsRequest = new GetJournalsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetJournalsResponse$Type extends MessageType<GetJournalsResponse> {
    constructor() {
        super("bitnode_console.journals.v1.GetJournalsResponse", [
            { no: 1, name: "entries", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => JournalsEntry },
            { no: 2, name: "pagination", kind: "message", T: () => PageResponse }
        ]);
    }
    create(value?: PartialMessage<GetJournalsResponse>): GetJournalsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.entries = [];
        if (value !== undefined)
            reflectionMergePartial<GetJournalsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetJournalsResponse): GetJournalsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated bitnode_console.journals.v1.JournalsEntry entries */ 1:
                    message.entries.push(JournalsEntry.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* bitnode_console.common.v1.PageResponse pagination */ 2:
                    message.pagination = PageResponse.internalBinaryRead(reader, reader.uint32(), options, message.pagination);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetJournalsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated bitnode_console.journals.v1.JournalsEntry entries = 1; */
        for (let i = 0; i < message.entries.length; i++)
            JournalsEntry.internalBinaryWrite(message.entries[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bitnode_console.common.v1.PageResponse pagination = 2; */
        if (message.pagination)
            PageResponse.internalBinaryWrite(message.pagination, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.journals.v1.GetJournalsResponse
 */
export const GetJournalsResponse = new GetJournalsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamJournalsRequest$Type extends MessageType<StreamJournalsRequest> {
    constructor() {
        super("bitnode_console.journals.v1.StreamJournalsRequest", [
            { no: 1, name: "tail_lines", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<StreamJournalsRequest>): StreamJournalsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.tailLines = 0;
        if (value !== undefined)
            reflectionMergePartial<StreamJournalsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamJournalsRequest): StreamJournalsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint32 tail_lines */ 1:
                    message.tailLines = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamJournalsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint32 tail_lines = 1; */
        if (message.tailLines !== 0)
            writer.tag(1, WireType.Varint).uint32(message.tailLines);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.journals.v1.StreamJournalsRequest
 */
export const StreamJournalsRequest = new StreamJournalsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class JournalsEntry$Type extends MessageType<JournalsEntry> {
    constructor() {
        super("bitnode_console.journals.v1.JournalsEntry", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "timestamp_us", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "priority", kind: "enum", T: () => ["bitnode_console.journals.v1.Priority", Priority, "PRIORITY_"] },
            { no: 4, name: "unit", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "cursor", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "extra_fields", kind: "map", K: 9 /*ScalarType.STRING*/, V: { kind: "scalar", T: 9 /*ScalarType.STRING*/ } }
        ]);
    }
    create(value?: PartialMessage<JournalsEntry>): JournalsEntry {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.message = "";
        message.timestampUs = "0";
        message.priority = 0;
        message.unit = "";
        message.extraFields = {};
        if (value !== undefined)
            reflectionMergePartial<JournalsEntry>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: JournalsEntry): JournalsEntry {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string message */ 1:
                    message.message = reader.string();
                    break;
                case /* int64 timestamp_us */ 2:
                    message.timestampUs = reader.int64().toString();
                    break;
                case /* bitnode_console.journals.v1.Priority priority */ 3:
                    message.priority = reader.int32();
                    break;
                case /* string unit */ 4:
                    message.unit = reader.string();
                    break;
                case /* optional string cursor */ 5:
                    message.cursor = reader.string();
                    break;
                case /* map<string, string> extra_fields */ 6:
                    this.binaryReadMap6(message.extraFields, reader, options);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    private binaryReadMap6(map: JournalsEntry["extraFields"], reader: IBinaryReader, options: BinaryReadOptions): void {
        let len = reader.uint32(), end = reader.pos + len, key: keyof JournalsEntry["extraFields"] | undefined, val: JournalsEntry["extraFields"][any] | undefined;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case 1:
                    key = reader.string();
                    break;
                case 2:
                    val = reader.string();
                    break;
                default: throw new globalThis.Error("unknown map entry field for bitnode_console.journals.v1.JournalsEntry.extra_fields");
            }
        }
        map[key ?? ""] = val ?? "";
    }
    internalBinaryWrite(message: JournalsEntry, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string message = 1; */
        if (message.message !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.message);
        /* int64 timestamp_us = 2; */
        if (message.timestampUs !== "0")
            writer.tag(2, WireType.Varint).int64(message.timestampUs);
        /* bitnode_console.journals.v1.Priority priority = 3; */
        if (message.priority !== 0)
            writer.tag(3, WireType.Varint).int32(message.priority);
        /* string unit = 4; */
        if (message.unit !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.unit);
        /* optional string cursor = 5; */
        if (message.cursor !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.cursor);
        /* map<string, string> extra_fields = 6; */
        for (let k of globalThis.Object.keys(message.extraFields))
            writer.tag(6, WireType.LengthDelimited).fork().tag(1, WireType.LengthDelimited).string(k).tag(2, WireType.LengthDelimited).string(message.extraFields[k]).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message bitnode_console.journals.v1.JournalsEntry
 */
export const JournalsEntry = new JournalsEntry$Type();
/**
 * @generated ServiceType for protobuf service bitnode_console.journals.v1.JournalsService
 */
export const JournalsService = new ServiceType("bitnode_console.journals.v1.JournalsService", [
    { name: "GetJournals", options: {}, I: GetJournalsRequest, O: GetJournalsResponse },
    { name: "StreamJournals", serverStreaming: true, options: {}, I: StreamJournalsRequest, O: JournalsEntry }
]);
