[package]
name = "lib_rpc"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
# Inherit lint configuration from the workspace Cargo.toml
workspace = true

[dependencies]
## --- Internal Dependencies
lib_tracing = { path = "../../libs/lib_tracing" }

## --- Workspace Dependencies
prost = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }

## --- Library Dependencies

[build-dependencies]
tonic-build = { workspace = true }

[dev-dependencies]
