[package]
name = "lib_auth"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
# Inherit lint configuration from the workspace Cargo.toml
workspace = true

[dependencies]
## --- Internal Dependencies

## --- Workspace Dependencies
secrecy = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

## --- Library Dependencies
argon2 = { version = "0.5.3" }
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
password-hash = { version = "0.5.0", features = ["getrandom"] }

[build-dependencies]

[dev-dependencies]
