[package]
name = "lib_journals"
description.workspace = true
repository.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lints]
# Inherit lint configuration from the workspace Cargo.toml
workspace = true

[dependencies]
## --- Internal Library Dependencies
lib_core = { path = "../../libs/lib_core" }

## --- Workspace Crate Dependencies
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

## --- Library Dependencies
async-stream = { version = "0.3.6" }
systemd = { version = "0.10.1" }

[build-dependencies]

[dev-dependencies]
