// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/v1/utilities.proto" (package "bitnode_console.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Utilities Service Protocol Buffer Definition
//
// Defines the RPC service and messages for utility operations,
// such as health-check pings.
//
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UtilitiesService } from "./utilities";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PingResponse } from "./utilities";
import type { PingRequest } from "./utilities";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * UtilitiesService exposes miscellaneous utility RPCs.
 *
 * @generated from protobuf service bitnode_console.v1.UtilitiesService
 */
export interface IUtilitiesServiceClient {
    /**
     * Ping verifies that the server is reachable and responding.
     *
     * @generated from protobuf rpc: Ping
     */
    ping(input: PingRequest, options?: RpcOptions): UnaryCall<PingRequest, PingResponse>;
}
/**
 * UtilitiesService exposes miscellaneous utility RPCs.
 *
 * @generated from protobuf service bitnode_console.v1.UtilitiesService
 */
export class UtilitiesServiceClient implements IUtilitiesServiceClient, ServiceInfo {
    typeName = UtilitiesService.typeName;
    methods = UtilitiesService.methods;
    options = UtilitiesService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Ping verifies that the server is reachable and responding.
     *
     * @generated from protobuf rpc: Ping
     */
    ping(input: PingRequest, options?: RpcOptions): UnaryCall<PingRequest, PingResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PingRequest, PingResponse>("unary", this._transport, method, opt, input);
    }
}
