// @ts-nocheck
// @generated by protobuf-ts 2.11.1 with parameter long_type_string
// @generated from protobuf file "bitnode_console/v1/journald/journald.proto" (package "bitnode_console.v1.journald.v1", syntax proto3)
// tslint:disable
//
// BitNode-Console Journald Service Protocol Buffer Definition
//
// Defines the RPC service and messages for reading Bitcoin daemon
// log entries from the systemd journal.
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { JournaldService } from "./journald";
import type { LogEntry } from "./journald";
import type { StreamLogsRequest } from "./journald";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetLogsResponse } from "./journald";
import type { GetLogsRequest } from "./journald";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * JournaldService exposes Bitcoin daemon log entries from the systemd journal.
 *
 * The unit name read is fixed by server configuration; clients cannot select
 * an arbitrary unit, preventing authenticated users from reading unrelated logs.
 *
 * @generated from protobuf service bitnode_console.v1.journald.v1.JournaldService
 */
export interface IJournaldServiceClient {
    /**
     * GetLogs returns the last N log lines (unary, for initial page load).
     *
     * @generated from protobuf rpc: GetLogs
     */
    getLogs(input: GetLogsRequest, options?: RpcOptions): UnaryCall<GetLogsRequest, GetLogsResponse>;
    /**
     * StreamLogs streams new log entries in real time (server-streaming, for live tail).
     *
     * @generated from protobuf rpc: StreamLogs
     */
    streamLogs(input: StreamLogsRequest, options?: RpcOptions): ServerStreamingCall<StreamLogsRequest, LogEntry>;
}
/**
 * JournaldService exposes Bitcoin daemon log entries from the systemd journal.
 *
 * The unit name read is fixed by server configuration; clients cannot select
 * an arbitrary unit, preventing authenticated users from reading unrelated logs.
 *
 * @generated from protobuf service bitnode_console.v1.journald.v1.JournaldService
 */
export class JournaldServiceClient implements IJournaldServiceClient, ServiceInfo {
    typeName = JournaldService.typeName;
    methods = JournaldService.methods;
    options = JournaldService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * GetLogs returns the last N log lines (unary, for initial page load).
     *
     * @generated from protobuf rpc: GetLogs
     */
    getLogs(input: GetLogsRequest, options?: RpcOptions): UnaryCall<GetLogsRequest, GetLogsResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLogsRequest, GetLogsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * StreamLogs streams new log entries in real time (server-streaming, for live tail).
     *
     * @generated from protobuf rpc: StreamLogs
     */
    streamLogs(input: StreamLogsRequest, options?: RpcOptions): ServerStreamingCall<StreamLogsRequest, LogEntry> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamLogsRequest, LogEntry>("serverStreaming", this._transport, method, opt, input);
    }
}
