# .github/workflows/mkdocks.yaml
name: mkdocs
on:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/actions/setup-python
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - run: pip install mkdocs mkdocs-material pymdown-extensions
      # Repository > Settings > Actions > General > Workflow permissions > Read and write permissions
      - run: mkdocs gh-deploy --force --clean --verbose

# Repository > Settings > Pages > Build and deployment > Branch > gh-pages

## References
# https://github.com/Neoteroi/mkdocs-plugins
